# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/bb/work/probe_basic-pyqt5-x86-dev/sources/debian/python3-probe-basic/usr/share/configs/machine_setup_files/user_atc_buttons/template_user_atc_buttons/template_user_atc_buttons.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_USER_ATC_BUTTONS(object):
    def setupUi(self, USER_ATC_BUTTONS):
        USER_ATC_BUTTONS.setObjectName("USER_ATC_BUTTONS")
        USER_ATC_BUTTONS.resize(299, 508)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(USER_ATC_BUTTONS.sizePolicy().hasHeightForWidth())
        USER_ATC_BUTTONS.setSizePolicy(sizePolicy)
        USER_ATC_BUTTONS.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalLayout = QtWidgets.QVBoxLayout(USER_ATC_BUTTONS)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_64 = QtWidgets.QWidget(USER_ATC_BUTTONS)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_64.sizePolicy().hasHeightForWidth())
        self.widget_64.setSizePolicy(sizePolicy)
        self.widget_64.setMinimumSize(QtCore.QSize(300, 0))
        self.widget_64.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget_64.setStyleSheet(".QWidget {\n"
"    background-color: rgb(51, 57, 59);\n"
"    border-style: solid;\n"
"    border-color: rgb(186, 189, 182);\n"
"    border-width: 2px;\n"
"    border-radius: 6px;\n"
"}")
        self.widget_64.setObjectName("widget_64")
        self.verticalLayout_66 = QtWidgets.QVBoxLayout(self.widget_64)
        self.verticalLayout_66.setContentsMargins(20, 18, 20, 21)
        self.verticalLayout_66.setSpacing(16)
        self.verticalLayout_66.setObjectName("verticalLayout_66")
        self.horizontalLayout_115 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_115.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_115.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_115.setSpacing(15)
        self.horizontalLayout_115.setObjectName("horizontalLayout_115")
        self.atc_rev_button = MDIButton(self.widget_64)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.atc_rev_button.sizePolicy().hasHeightForWidth())
        self.atc_rev_button.setSizePolicy(sizePolicy)
        self.atc_rev_button.setMinimumSize(QtCore.QSize(120, 45))
        self.atc_rev_button.setMaximumSize(QtCore.QSize(16777215, 45))
        self.atc_rev_button.setMouseTracking(True)
        self.atc_rev_button.setTabletTracking(False)
        self.atc_rev_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.atc_rev_button.setToolTipDuration(-1)
        self.atc_rev_button.setStyleSheet("MDIButton {\n"
"    font: 15pt \"Bebas Kai\";\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/ccw_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.atc_rev_button.setIcon(icon)
        self.atc_rev_button.setIconSize(QtCore.QSize(20, 20))
        self.atc_rev_button.setObjectName("atc_rev_button")
        self.horizontalLayout_115.addWidget(self.atc_rev_button)
        self.atc_fwd_button = MDIButton(self.widget_64)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.atc_fwd_button.sizePolicy().hasHeightForWidth())
        self.atc_fwd_button.setSizePolicy(sizePolicy)
        self.atc_fwd_button.setMinimumSize(QtCore.QSize(120, 45))
        self.atc_fwd_button.setMaximumSize(QtCore.QSize(16777215, 45))
        self.atc_fwd_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.atc_fwd_button.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.atc_fwd_button.setStyleSheet("MDIButton {\n"
"    font: 15pt \"Bebas Kai\";\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/cw_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.atc_fwd_button.setIcon(icon1)
        self.atc_fwd_button.setIconSize(QtCore.QSize(20, 20))
        self.atc_fwd_button.setObjectName("atc_fwd_button")
        self.horizontalLayout_115.addWidget(self.atc_fwd_button)
        self.verticalLayout_66.addLayout(self.horizontalLayout_115)
        self.horizontalLayout_116 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_116.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_116.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_116.setSpacing(15)
        self.horizontalLayout_116.setObjectName("horizontalLayout_116")
        self.atc_retract_button = SubCallButton(self.widget_64)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.atc_retract_button.sizePolicy().hasHeightForWidth())
        self.atc_retract_button.setSizePolicy(sizePolicy)
        self.atc_retract_button.setMinimumSize(QtCore.QSize(120, 45))
        self.atc_retract_button.setMaximumSize(QtCore.QSize(16777215, 45))
        self.atc_retract_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.atc_retract_button.setStyleSheet("SubCallButton {\n"
"    color: white;\n"
"    border-color: black;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    border-width: 2px;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(213, 218, 216, 255), stop:0.169312 rgba(82, 82, 83, 255), stop:0.328042 rgba(72, 70, 73, 255), stop:0.492063 rgba(78, 77, 79, 255), stop:0.703704 rgba(72, 70, 73, 255), stop:0.86 rgba(82, 82, 83, 255), stop:1 rgba(213, 218, 216, 255));\n"
"    font-family: \"Bebas Kai\";\n"
"    font-size: 15pt;\n"
"}\n"
"\n"
"SubCallButton:disabled {\n"
"    border-color: gray;\n"
"}\n"
"\n"
"SubCallButton:hover {\n"
"    background:  qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #A19E9E, stop: 1.0 #5C5959);\n"
"}\n"
"\n"
"SubCallButton:pressed {\n"
"    background:  qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(85, 85, 238, 255), stop:0.544974 rgba(90, 91, 239, 255), stop:1 rgba(126, 135, 243, 255));\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/left_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.atc_retract_button.setIcon(icon2)
        self.atc_retract_button.setIconSize(QtCore.QSize(20, 20))
        self.atc_retract_button.setObjectName("atc_retract_button")
        self.horizontalLayout_116.addWidget(self.atc_retract_button)
        self.atc_extend_button = SubCallButton(self.widget_64)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.atc_extend_button.sizePolicy().hasHeightForWidth())
        self.atc_extend_button.setSizePolicy(sizePolicy)
        self.atc_extend_button.setMinimumSize(QtCore.QSize(120, 45))
        self.atc_extend_button.setMaximumSize(QtCore.QSize(16777215, 45))
        self.atc_extend_button.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.atc_extend_button.setStyleSheet("SubCallButton {\n"
"    color: white;\n"
"    border-color: black;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    border-width: 2px;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(213, 218, 216, 255), stop:0.169312 rgba(82, 82, 83, 255), stop:0.328042 rgba(72, 70, 73, 255), stop:0.492063 rgba(78, 77, 79, 255), stop:0.703704 rgba(72, 70, 73, 255), stop:0.86 rgba(82, 82, 83, 255), stop:1 rgba(213, 218, 216, 255));\n"
"    font-family: \"Bebas Kai\";\n"
"    font-size: 15pt;\n"
"}\n"
"\n"
"SubCallButton:disabled {\n"
"    border-color: gray;\n"
"}\n"
"\n"
"SubCallButton:hover {\n"
"    background:  qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #A19E9E, stop: 1.0 #5C5959);\n"
"}\n"
"\n"
"SubCallButton:pressed {\n"
"    background:  qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(85, 85, 238, 255), stop:0.544974 rgba(90, 91, 239, 255), stop:1 rgba(126, 135, 243, 255));\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/right_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.atc_extend_button.setIcon(icon3)
        self.atc_extend_button.setIconSize(QtCore.QSize(20, 20))
        self.atc_extend_button.setObjectName("atc_extend_button")
        self.horizontalLayout_116.addWidget(self.atc_extend_button)
        self.verticalLayout_66.addLayout(self.horizontalLayout_116)
        self.horizontalLayout_117 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_117.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_117.setSpacing(15)
        self.horizontalLayout_117.setObjectName("horizontalLayout_117")
        self.clamp_tool_button = SubCallButton(self.widget_64)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clamp_tool_button.sizePolicy().hasHeightForWidth())
        self.clamp_tool_button.setSizePolicy(sizePolicy)
        self.clamp_tool_button.setMinimumSize(QtCore.QSize(120, 45))
        self.clamp_tool_button.setMaximumSize(QtCore.QSize(16777215, 45))
        self.clamp_tool_button.setStyleSheet("SubCallButton {\n"
"    color: white;\n"
"    border-color: black;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    border-width: 2px;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(213, 218, 216, 255), stop:0.169312 rgba(82, 82, 83, 255), stop:0.328042 rgba(72, 70, 73, 255), stop:0.492063 rgba(78, 77, 79, 255), stop:0.703704 rgba(72, 70, 73, 255), stop:0.86 rgba(82, 82, 83, 255), stop:1 rgba(213, 218, 216, 255));\n"
"    font-family: \"Bebas Kai\";\n"
"    font-size: 15pt;\n"
"}\n"
"\n"
"SubCallButton:disabled {\n"
"    border-color: gray;\n"
"}\n"
"\n"
"SubCallButton:hover {\n"
"    background:  qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #A19E9E, stop: 1.0 #5C5959);\n"
"}\n"
"\n"
"SubCallButton:pressed {\n"
"    background:  qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(85, 85, 238, 255), stop:0.544974 rgba(90, 91, 239, 255), stop:1 rgba(126, 135, 243, 255));\n"
"}\n"
"")
        self.clamp_tool_button.setObjectName("clamp_tool_button")
        self.horizontalLayout_117.addWidget(self.clamp_tool_button)
        self.release_tool_button = SubCallButton(self.widget_64)
        self.release_tool_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.release_tool_button.sizePolicy().hasHeightForWidth())
        self.release_tool_button.setSizePolicy(sizePolicy)
        self.release_tool_button.setMinimumSize(QtCore.QSize(120, 45))
        self.release_tool_button.setMaximumSize(QtCore.QSize(16777215, 45))
        self.release_tool_button.setStyleSheet("SubCallButton {\n"
"    color: white;\n"
"    border-color: black;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    border-width: 2px;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(213, 218, 216, 255), stop:0.169312 rgba(82, 82, 83, 255), stop:0.328042 rgba(72, 70, 73, 255), stop:0.492063 rgba(78, 77, 79, 255), stop:0.703704 rgba(72, 70, 73, 255), stop:0.86 rgba(82, 82, 83, 255), stop:1 rgba(213, 218, 216, 255));\n"
"    font-family: \"Bebas Kai\";\n"
"    font-size: 15pt;\n"
"}\n"
"\n"
"SubCallButton:disabled {\n"
"    border-color: gray;\n"
"}\n"
"\n"
"SubCallButton:hover {\n"
"    background:  qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #A19E9E, stop: 1.0 #5C5959);\n"
"}\n"
"\n"
"SubCallButton:pressed {\n"
"    background:  qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(85, 85, 238, 255), stop:0.544974 rgba(90, 91, 239, 255), stop:1 rgba(126, 135, 243, 255));\n"
"}\n"
"")
        self.release_tool_button.setObjectName("release_tool_button")
        self.horizontalLayout_117.addWidget(self.release_tool_button)
        self.verticalLayout_66.addLayout(self.horizontalLayout_117)
        self.horizontalLayout_152 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_152.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_152.setSpacing(15)
        self.horizontalLayout_152.setObjectName("horizontalLayout_152")
        self.spindle_orientation = SubCallButton(self.widget_64)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spindle_orientation.sizePolicy().hasHeightForWidth())
        self.spindle_orientation.setSizePolicy(sizePolicy)
        self.spindle_orientation.setMinimumSize(QtCore.QSize(120, 45))
        self.spindle_orientation.setMaximumSize(QtCore.QSize(16777215, 45))
        self.spindle_orientation.setStyleSheet("SubCallButton {\n"
"    color: white;\n"
"    border-color: black;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    border-width: 2px;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(213, 218, 216, 255), stop:0.169312 rgba(82, 82, 83, 255), stop:0.328042 rgba(72, 70, 73, 255), stop:0.492063 rgba(78, 77, 79, 255), stop:0.703704 rgba(72, 70, 73, 255), stop:0.86 rgba(82, 82, 83, 255), stop:1 rgba(213, 218, 216, 255));\n"
"    font-family: \"Bebas Kai\";\n"
"    font-size: 15pt;\n"
"}\n"
"\n"
"SubCallButton:disabled {\n"
"    border-color: gray;\n"
"}\n"
"\n"
"SubCallButton:hover {\n"
"    background:  qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #A19E9E, stop: 1.0 #5C5959);\n"
"}\n"
"\n"
"SubCallButton:pressed {\n"
"    background:  qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(85, 85, 238, 255), stop:0.544974 rgba(90, 91, 239, 255), stop:1 rgba(126, 135, 243, 255));\n"
"}\n"
"")
        self.spindle_orientation.setCheckable(True)
        self.spindle_orientation.setObjectName("spindle_orientation")
        self.horizontalLayout_152.addWidget(self.spindle_orientation)
        self.unlock_spindle = MDIButton(self.widget_64)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unlock_spindle.sizePolicy().hasHeightForWidth())
        self.unlock_spindle.setSizePolicy(sizePolicy)
        self.unlock_spindle.setMinimumSize(QtCore.QSize(120, 45))
        self.unlock_spindle.setMaximumSize(QtCore.QSize(16777215, 45))
        self.unlock_spindle.setFocusPolicy(QtCore.Qt.NoFocus)
        self.unlock_spindle.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.unlock_spindle.setStyleSheet("MDIButton {\n"
"    font: 15pt \"Bebas Kai\";\n"
"}")
        self.unlock_spindle.setIconSize(QtCore.QSize(20, 20))
        self.unlock_spindle.setObjectName("unlock_spindle")
        self.horizontalLayout_152.addWidget(self.unlock_spindle)
        self.verticalLayout_66.addLayout(self.horizontalLayout_152)
        self.horizontalLayout_174 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_174.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_174.setSpacing(15)
        self.horizontalLayout_174.setObjectName("horizontalLayout_174")
        self.move_head_above_carousel_button = SubCallButton(self.widget_64)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.move_head_above_carousel_button.sizePolicy().hasHeightForWidth())
        self.move_head_above_carousel_button.setSizePolicy(sizePolicy)
        self.move_head_above_carousel_button.setMinimumSize(QtCore.QSize(120, 45))
        self.move_head_above_carousel_button.setMaximumSize(QtCore.QSize(16777215, 45))
        self.move_head_above_carousel_button.setStyleSheet("SubCallButton {\n"
"    color: white;\n"
"    border-color: black;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    border-width: 2px;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(213, 218, 216, 255), stop:0.169312 rgba(82, 82, 83, 255), stop:0.328042 rgba(72, 70, 73, 255), stop:0.492063 rgba(78, 77, 79, 255), stop:0.703704 rgba(72, 70, 73, 255), stop:0.86 rgba(82, 82, 83, 255), stop:1 rgba(213, 218, 216, 255));\n"
"    font-family: \"Bebas Kai\";\n"
"    font-size: 15pt;\n"
"}\n"
"\n"
"SubCallButton:disabled {\n"
"    border-color: gray;\n"
"}\n"
"\n"
"SubCallButton:hover {\n"
"    background:  qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #A19E9E, stop: 1.0 #5C5959);\n"
"}\n"
"\n"
"SubCallButton:pressed {\n"
"    background:  qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(85, 85, 238, 255), stop:0.544974 rgba(90, 91, 239, 255), stop:1 rgba(126, 135, 243, 255));\n"
"}\n"
"")
        self.move_head_above_carousel_button.setObjectName("move_head_above_carousel_button")
        self.horizontalLayout_174.addWidget(self.move_head_above_carousel_button)
        self.verticalLayout_66.addLayout(self.horizontalLayout_174)
        self.horizontalLayout_118 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_118.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_118.setSpacing(15)
        self.horizontalLayout_118.setObjectName("horizontalLayout_118")
        self.move_tool_to_carousel_height_button = SubCallButton(self.widget_64)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.move_tool_to_carousel_height_button.sizePolicy().hasHeightForWidth())
        self.move_tool_to_carousel_height_button.setSizePolicy(sizePolicy)
        self.move_tool_to_carousel_height_button.setMinimumSize(QtCore.QSize(120, 45))
        self.move_tool_to_carousel_height_button.setMaximumSize(QtCore.QSize(16777215, 45))
        self.move_tool_to_carousel_height_button.setStyleSheet("SubCallButton {\n"
"    color: white;\n"
"    border-color: black;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    border-width: 2px;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(213, 218, 216, 255), stop:0.169312 rgba(82, 82, 83, 255), stop:0.328042 rgba(72, 70, 73, 255), stop:0.492063 rgba(78, 77, 79, 255), stop:0.703704 rgba(72, 70, 73, 255), stop:0.86 rgba(82, 82, 83, 255), stop:1 rgba(213, 218, 216, 255));\n"
"    font-family: \"Bebas Kai\";\n"
"    font-size: 15pt;\n"
"}\n"
"\n"
"SubCallButton:disabled {\n"
"    border-color: gray;\n"
"}\n"
"\n"
"SubCallButton:hover {\n"
"    background:  qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #A19E9E, stop: 1.0 #5C5959);\n"
"}\n"
"\n"
"SubCallButton:pressed {\n"
"    background:  qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(85, 85, 238, 255), stop:0.544974 rgba(90, 91, 239, 255), stop:1 rgba(126, 135, 243, 255));\n"
"}\n"
"")
        self.move_tool_to_carousel_height_button.setObjectName("move_tool_to_carousel_height_button")
        self.horizontalLayout_118.addWidget(self.move_tool_to_carousel_height_button)
        self.verticalLayout_66.addLayout(self.horizontalLayout_118)
        self.label_20 = QtWidgets.QLabel(self.widget_64)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_66.addWidget(self.label_20)
        self.horizontalLayout_119 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_119.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_119.setSpacing(15)
        self.horizontalLayout_119.setObjectName("horizontalLayout_119")
        self.reference_carousel = MDIButton(self.widget_64)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reference_carousel.sizePolicy().hasHeightForWidth())
        self.reference_carousel.setSizePolicy(sizePolicy)
        self.reference_carousel.setMinimumSize(QtCore.QSize(125, 45))
        self.reference_carousel.setMaximumSize(QtCore.QSize(16777215, 45))
        self.reference_carousel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.reference_carousel.setStyleSheet("MDIButton {\n"
"    font: 15pt \"Bebas Kai\";\n"
"}")
        self.reference_carousel.setIconSize(QtCore.QSize(20, 20))
        self.reference_carousel.setObjectName("reference_carousel")
        self.horizontalLayout_119.addWidget(self.reference_carousel)
        self.verticalLayout_66.addLayout(self.horizontalLayout_119)
        self.verticalLayout.addWidget(self.widget_64)

        self.retranslateUi(USER_ATC_BUTTONS)
        QtCore.QMetaObject.connectSlotsByName(USER_ATC_BUTTONS)

    def retranslateUi(self, USER_ATC_BUTTONS):
        _translate = QtCore.QCoreApplication.translate
        USER_ATC_BUTTONS.setWindowTitle(_translate("USER_ATC_BUTTONS", "User Atc Buttons"))
        self.atc_rev_button.setToolTip(_translate("USER_ATC_BUTTONS", "M11P1 User Defined Macro Call from Subroutine Folder"))
        self.atc_rev_button.setText(_translate("USER_ATC_BUTTONS", " ATC REV"))
        self.atc_rev_button.setProperty("MDICommand", _translate("USER_ATC_BUTTONS", "M12P1"))
        self.atc_fwd_button.setToolTip(_translate("USER_ATC_BUTTONS", "M12 P1 User Defined Macro Call from Subroutine Folder"))
        self.atc_fwd_button.setText(_translate("USER_ATC_BUTTONS", " ATC FWD "))
        self.atc_fwd_button.setProperty("MDICommand", _translate("USER_ATC_BUTTONS", "M11P1"))
        self.atc_retract_button.setText(_translate("USER_ATC_BUTTONS", "  ATC RETRACT"))
        self.atc_retract_button.setProperty("filename", _translate("USER_ATC_BUTTONS", "retractatc.ngc"))
        self.atc_extend_button.setText(_translate("USER_ATC_BUTTONS", "ATC EXTEND  "))
        self.atc_extend_button.setProperty("filename", _translate("USER_ATC_BUTTONS", "extendatc.ngc"))
        self.clamp_tool_button.setText(_translate("USER_ATC_BUTTONS", "CLAMP TOOL"))
        self.clamp_tool_button.setProperty("filename", _translate("USER_ATC_BUTTONS", "clamptool.ngc"))
        self.release_tool_button.setText(_translate("USER_ATC_BUTTONS", "RELEASE TOOL"))
        self.release_tool_button.setProperty("rules", _translate("USER_ATC_BUTTONS", "[{\"name\": \"New Rule\", \"property\": \"Enable\", \"expression\": \"not ch[0]\", \"channels\": [{\"url\": \"status:spindle.0.enabled\", \"trigger\": true}]}]"))
        self.release_tool_button.setProperty("filename", _translate("USER_ATC_BUTTONS", "unclamptool.ngc"))
        self.spindle_orientation.setText(_translate("USER_ATC_BUTTONS", "ORIENT SPINDLE"))
        self.spindle_orientation.setProperty("filename", _translate("USER_ATC_BUTTONS", "orientspindle.ngc"))
        self.unlock_spindle.setToolTip(_translate("USER_ATC_BUTTONS", "M112 User Defined Macro Call from Subroutine Folder"))
        self.unlock_spindle.setText(_translate("USER_ATC_BUTTONS", "UNLOCK SPINDLE"))
        self.unlock_spindle.setProperty("MDICommand", _translate("USER_ATC_BUTTONS", "M5"))
        self.move_head_above_carousel_button.setText(_translate("USER_ATC_BUTTONS", "MOVE HEAD ABOVE CAROUSEL"))
        self.move_head_above_carousel_button.setProperty("filename", _translate("USER_ATC_BUTTONS", "move_head_above_carousel.ngc"))
        self.move_tool_to_carousel_height_button.setText(_translate("USER_ATC_BUTTONS", "MOVE TOOL TO CAROUSEL HEIGHT"))
        self.move_tool_to_carousel_height_button.setProperty("filename", _translate("USER_ATC_BUTTONS", "move_tool_to_carousel_height.ngc"))
        self.reference_carousel.setToolTip(_translate("USER_ATC_BUTTONS", "M13 User Defined Macro Call from Subroutine Folder"))
        self.reference_carousel.setText(_translate("USER_ATC_BUTTONS", "REF CAROUSEL"))
        self.reference_carousel.setProperty("MDICommand", _translate("USER_ATC_BUTTONS", "M13"))
from qtpyvcp.widgets.button_widgets.mdi_button import MDIButton
from qtpyvcp.widgets.button_widgets.subcall_button import SubCallButton
import probe_basic_rc
