# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/bb/work/probe_basic-pyqt5-x86-dev/sources/debian/python3-probe-basic/usr/share/configs/machine_setup_files/user_atc_buttons/template_user_rack_atc_buttons/template_user_rack_atc_buttons.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_USER_ATC_BUTTONS(object):
    def setupUi(self, USER_ATC_BUTTONS):
        USER_ATC_BUTTONS.setObjectName("USER_ATC_BUTTONS")
        USER_ATC_BUTTONS.resize(300, 429)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(USER_ATC_BUTTONS.sizePolicy().hasHeightForWidth())
        USER_ATC_BUTTONS.setSizePolicy(sizePolicy)
        USER_ATC_BUTTONS.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalLayout = QtWidgets.QVBoxLayout(USER_ATC_BUTTONS)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_64 = QtWidgets.QFrame(USER_ATC_BUTTONS)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_64.sizePolicy().hasHeightForWidth())
        self.frame_64.setSizePolicy(sizePolicy)
        self.frame_64.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_64.setStyleSheet("")
        self.frame_64.setObjectName("frame_64")
        self.verticalLayout_66 = QtWidgets.QVBoxLayout(self.frame_64)
        self.verticalLayout_66.setContentsMargins(20, 18, 20, 18)
        self.verticalLayout_66.setSpacing(16)
        self.verticalLayout_66.setObjectName("verticalLayout_66")
        self.work_column_header_8 = QtWidgets.QLabel(self.frame_64)
        self.work_column_header_8.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.work_column_header_8.sizePolicy().hasHeightForWidth())
        self.work_column_header_8.setSizePolicy(sizePolicy)
        self.work_column_header_8.setMinimumSize(QtCore.QSize(0, 38))
        self.work_column_header_8.setMaximumSize(QtCore.QSize(16777215, 38))
        self.work_column_header_8.setStyleSheet("QLabel{\n"
"    border-style: solid;\n"
"    border-color: rgb(176, 179, 172);\n"
"    border-width: 2px;\n"
"    border-radius: 5px;\n"
"    color: white;\n"
"    background: rgb(90, 90, 90);\n"
"    font: 16pt \"Bebas Kai\";\n"
"}")
        self.work_column_header_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.work_column_header_8.setAlignment(QtCore.Qt.AlignCenter)
        self.work_column_header_8.setWordWrap(True)
        self.work_column_header_8.setIndent(0)
        self.work_column_header_8.setObjectName("work_column_header_8")
        self.verticalLayout_66.addWidget(self.work_column_header_8)
        self.horizontalLayout_119 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_119.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_119.setSpacing(15)
        self.horizontalLayout_119.setObjectName("horizontalLayout_119")
        self.reference_carousel_3 = MDIButton(self.frame_64)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reference_carousel_3.sizePolicy().hasHeightForWidth())
        self.reference_carousel_3.setSizePolicy(sizePolicy)
        self.reference_carousel_3.setMinimumSize(QtCore.QSize(120, 45))
        self.reference_carousel_3.setMaximumSize(QtCore.QSize(16777215, 45))
        self.reference_carousel_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.reference_carousel_3.setStyleSheet("MDIButton {\n"
"    font: 15pt \"Bebas Kai\";\n"
"}")
        self.reference_carousel_3.setIconSize(QtCore.QSize(20, 20))
        self.reference_carousel_3.setObjectName("reference_carousel_3")
        self.horizontalLayout_119.addWidget(self.reference_carousel_3)
        self.reference_carousel_4 = MDIButton(self.frame_64)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reference_carousel_4.sizePolicy().hasHeightForWidth())
        self.reference_carousel_4.setSizePolicy(sizePolicy)
        self.reference_carousel_4.setMinimumSize(QtCore.QSize(120, 45))
        self.reference_carousel_4.setMaximumSize(QtCore.QSize(16777215, 45))
        self.reference_carousel_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.reference_carousel_4.setStyleSheet("MDIButton {\n"
"    font: 15pt \"Bebas Kai\";\n"
"}")
        self.reference_carousel_4.setIconSize(QtCore.QSize(20, 20))
        self.reference_carousel_4.setObjectName("reference_carousel_4")
        self.horizontalLayout_119.addWidget(self.reference_carousel_4)
        self.verticalLayout_66.addLayout(self.horizontalLayout_119)
        self.horizontalLayout_117 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_117.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_117.setSpacing(15)
        self.horizontalLayout_117.setObjectName("horizontalLayout_117")
        self.clamp_tool_button = SubCallButton(self.frame_64)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clamp_tool_button.sizePolicy().hasHeightForWidth())
        self.clamp_tool_button.setSizePolicy(sizePolicy)
        self.clamp_tool_button.setMinimumSize(QtCore.QSize(120, 45))
        self.clamp_tool_button.setMaximumSize(QtCore.QSize(16777215, 45))
        self.clamp_tool_button.setStyleSheet("SubCallButton {\n"
"    color: white;\n"
"    border-color: black;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    border-width: 2px;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(213, 218, 216, 255), stop:0.169312 rgba(82, 82, 83, 255), stop:0.328042 rgba(72, 70, 73, 255), stop:0.492063 rgba(78, 77, 79, 255), stop:0.703704 rgba(72, 70, 73, 255), stop:0.86 rgba(82, 82, 83, 255), stop:1 rgba(213, 218, 216, 255));\n"
"    font-family: \"Bebas Kai\";\n"
"    font-size: 15pt;\n"
"}\n"
"\n"
"SubCallButton:disabled {\n"
"    border-color: gray;\n"
"}\n"
"\n"
"SubCallButton:hover {\n"
"    background:  qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #A19E9E, stop: 1.0 #5C5959);\n"
"}\n"
"\n"
"SubCallButton:pressed {\n"
"    background:  qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(85, 85, 238, 255), stop:0.544974 rgba(90, 91, 239, 255), stop:1 rgba(126, 135, 243, 255));\n"
"}\n"
"")
        self.clamp_tool_button.setObjectName("clamp_tool_button")
        self.horizontalLayout_117.addWidget(self.clamp_tool_button)
        self.release_tool_button = SubCallButton(self.frame_64)
        self.release_tool_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.release_tool_button.sizePolicy().hasHeightForWidth())
        self.release_tool_button.setSizePolicy(sizePolicy)
        self.release_tool_button.setMinimumSize(QtCore.QSize(120, 45))
        self.release_tool_button.setMaximumSize(QtCore.QSize(16777215, 45))
        self.release_tool_button.setStyleSheet("SubCallButton {\n"
"    color: white;\n"
"    border-color: black;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    border-width: 2px;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(213, 218, 216, 255), stop:0.169312 rgba(82, 82, 83, 255), stop:0.328042 rgba(72, 70, 73, 255), stop:0.492063 rgba(78, 77, 79, 255), stop:0.703704 rgba(72, 70, 73, 255), stop:0.86 rgba(82, 82, 83, 255), stop:1 rgba(213, 218, 216, 255));\n"
"    font-family: \"Bebas Kai\";\n"
"    font-size: 15pt;\n"
"}\n"
"\n"
"SubCallButton:disabled {\n"
"    border-color: gray;\n"
"}\n"
"\n"
"SubCallButton:hover {\n"
"    background:  qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #A19E9E, stop: 1.0 #5C5959);\n"
"}\n"
"\n"
"SubCallButton:pressed {\n"
"    background:  qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(85, 85, 238, 255), stop:0.544974 rgba(90, 91, 239, 255), stop:1 rgba(126, 135, 243, 255));\n"
"}\n"
"")
        self.release_tool_button.setObjectName("release_tool_button")
        self.horizontalLayout_117.addWidget(self.release_tool_button)
        self.verticalLayout_66.addLayout(self.horizontalLayout_117)
        self.horizontalLayout_152 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_152.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_152.setSpacing(15)
        self.horizontalLayout_152.setObjectName("horizontalLayout_152")
        self.spindle_orientation = SubCallButton(self.frame_64)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spindle_orientation.sizePolicy().hasHeightForWidth())
        self.spindle_orientation.setSizePolicy(sizePolicy)
        self.spindle_orientation.setMinimumSize(QtCore.QSize(120, 45))
        self.spindle_orientation.setMaximumSize(QtCore.QSize(16777215, 45))
        self.spindle_orientation.setStyleSheet("SubCallButton {\n"
"    color: white;\n"
"    border-color: black;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    border-width: 2px;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(213, 218, 216, 255), stop:0.169312 rgba(82, 82, 83, 255), stop:0.328042 rgba(72, 70, 73, 255), stop:0.492063 rgba(78, 77, 79, 255), stop:0.703704 rgba(72, 70, 73, 255), stop:0.86 rgba(82, 82, 83, 255), stop:1 rgba(213, 218, 216, 255));\n"
"    font-family: \"Bebas Kai\";\n"
"    font-size: 15pt;\n"
"}\n"
"\n"
"SubCallButton:disabled {\n"
"    border-color: gray;\n"
"}\n"
"\n"
"SubCallButton:hover {\n"
"    background:  qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #A19E9E, stop: 1.0 #5C5959);\n"
"}\n"
"\n"
"SubCallButton:pressed {\n"
"    background:  qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(85, 85, 238, 255), stop:0.544974 rgba(90, 91, 239, 255), stop:1 rgba(126, 135, 243, 255));\n"
"}\n"
"")
        self.spindle_orientation.setCheckable(True)
        self.spindle_orientation.setObjectName("spindle_orientation")
        self.horizontalLayout_152.addWidget(self.spindle_orientation)
        self.unlock_spindle = MDIButton(self.frame_64)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unlock_spindle.sizePolicy().hasHeightForWidth())
        self.unlock_spindle.setSizePolicy(sizePolicy)
        self.unlock_spindle.setMinimumSize(QtCore.QSize(120, 45))
        self.unlock_spindle.setMaximumSize(QtCore.QSize(16777215, 45))
        self.unlock_spindle.setFocusPolicy(QtCore.Qt.NoFocus)
        self.unlock_spindle.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.unlock_spindle.setStyleSheet("MDIButton {\n"
"    font: 15pt \"Bebas Kai\";\n"
"}")
        self.unlock_spindle.setIconSize(QtCore.QSize(20, 20))
        self.unlock_spindle.setObjectName("unlock_spindle")
        self.horizontalLayout_152.addWidget(self.unlock_spindle)
        self.verticalLayout_66.addLayout(self.horizontalLayout_152)
        self.horizontalLayout_174 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_174.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_174.setSpacing(15)
        self.horizontalLayout_174.setObjectName("horizontalLayout_174")
        self.move_head_above_carousel_button = SubCallButton(self.frame_64)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.move_head_above_carousel_button.sizePolicy().hasHeightForWidth())
        self.move_head_above_carousel_button.setSizePolicy(sizePolicy)
        self.move_head_above_carousel_button.setMinimumSize(QtCore.QSize(120, 45))
        self.move_head_above_carousel_button.setMaximumSize(QtCore.QSize(16777215, 45))
        self.move_head_above_carousel_button.setStyleSheet("SubCallButton {\n"
"    color: white;\n"
"    border-color: black;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    border-width: 2px;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(213, 218, 216, 255), stop:0.169312 rgba(82, 82, 83, 255), stop:0.328042 rgba(72, 70, 73, 255), stop:0.492063 rgba(78, 77, 79, 255), stop:0.703704 rgba(72, 70, 73, 255), stop:0.86 rgba(82, 82, 83, 255), stop:1 rgba(213, 218, 216, 255));\n"
"    font-family: \"Bebas Kai\";\n"
"    font-size: 15pt;\n"
"}\n"
"\n"
"SubCallButton:disabled {\n"
"    border-color: gray;\n"
"}\n"
"\n"
"SubCallButton:hover {\n"
"    background:  qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #A19E9E, stop: 1.0 #5C5959);\n"
"}\n"
"\n"
"SubCallButton:pressed {\n"
"    background:  qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(85, 85, 238, 255), stop:0.544974 rgba(90, 91, 239, 255), stop:1 rgba(126, 135, 243, 255));\n"
"}\n"
"")
        self.move_head_above_carousel_button.setObjectName("move_head_above_carousel_button")
        self.horizontalLayout_174.addWidget(self.move_head_above_carousel_button)
        self.move_tool_to_carousel_height_button = SubCallButton(self.frame_64)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.move_tool_to_carousel_height_button.sizePolicy().hasHeightForWidth())
        self.move_tool_to_carousel_height_button.setSizePolicy(sizePolicy)
        self.move_tool_to_carousel_height_button.setMinimumSize(QtCore.QSize(120, 45))
        self.move_tool_to_carousel_height_button.setMaximumSize(QtCore.QSize(16777215, 45))
        self.move_tool_to_carousel_height_button.setStyleSheet("SubCallButton {\n"
"    color: white;\n"
"    border-color: black;\n"
"    border-style: solid;\n"
"    border-radius: 5px;\n"
"    border-width: 2px;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(213, 218, 216, 255), stop:0.169312 rgba(82, 82, 83, 255), stop:0.328042 rgba(72, 70, 73, 255), stop:0.492063 rgba(78, 77, 79, 255), stop:0.703704 rgba(72, 70, 73, 255), stop:0.86 rgba(82, 82, 83, 255), stop:1 rgba(213, 218, 216, 255));\n"
"    font-family: \"Bebas Kai\";\n"
"    font-size: 15pt;\n"
"}\n"
"\n"
"SubCallButton:disabled {\n"
"    border-color: gray;\n"
"}\n"
"\n"
"SubCallButton:hover {\n"
"    background:  qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #A19E9E, stop: 1.0 #5C5959);\n"
"}\n"
"\n"
"SubCallButton:pressed {\n"
"    background:  qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(85, 85, 238, 255), stop:0.544974 rgba(90, 91, 239, 255), stop:1 rgba(126, 135, 243, 255));\n"
"}\n"
"")
        self.move_tool_to_carousel_height_button.setObjectName("move_tool_to_carousel_height_button")
        self.horizontalLayout_174.addWidget(self.move_tool_to_carousel_height_button)
        self.verticalLayout_66.addLayout(self.horizontalLayout_174)
        self.widget_10 = QtWidgets.QWidget(self.frame_64)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_66.addWidget(self.widget_10)
        self.horizontalLayout_159 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_159.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_159.setSpacing(15)
        self.horizontalLayout_159.setObjectName("horizontalLayout_159")
        self.reference_carousel_2 = MDIButton(self.frame_64)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reference_carousel_2.sizePolicy().hasHeightForWidth())
        self.reference_carousel_2.setSizePolicy(sizePolicy)
        self.reference_carousel_2.setMinimumSize(QtCore.QSize(125, 45))
        self.reference_carousel_2.setMaximumSize(QtCore.QSize(16777215, 45))
        self.reference_carousel_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.reference_carousel_2.setStyleSheet("MDIButton {\n"
"    font: 15pt \"Bebas Kai\";\n"
"}")
        self.reference_carousel_2.setIconSize(QtCore.QSize(20, 20))
        self.reference_carousel_2.setObjectName("reference_carousel_2")
        self.horizontalLayout_159.addWidget(self.reference_carousel_2)
        self.verticalLayout_66.addLayout(self.horizontalLayout_159)
        self.verticalLayout.addWidget(self.frame_64)

        self.retranslateUi(USER_ATC_BUTTONS)
        QtCore.QMetaObject.connectSlotsByName(USER_ATC_BUTTONS)

    def retranslateUi(self, USER_ATC_BUTTONS):
        _translate = QtCore.QCoreApplication.translate
        USER_ATC_BUTTONS.setWindowTitle(_translate("USER_ATC_BUTTONS", "User Atc Buttons"))
        self.work_column_header_8.setText(_translate("USER_ATC_BUTTONS", "ATC MANUAL CONTROL PANEL"))
        self.reference_carousel_3.setToolTip(_translate("USER_ATC_BUTTONS", "M13 User Defined Macro Call from Subroutine Folder"))
        self.reference_carousel_3.setText(_translate("USER_ATC_BUTTONS", "AIR BLAST"))
        self.reference_carousel_3.setProperty("MDICommand", _translate("USER_ATC_BUTTONS", "M13"))
        self.reference_carousel_4.setToolTip(_translate("USER_ATC_BUTTONS", "M13 User Defined Macro Call from Subroutine Folder"))
        self.reference_carousel_4.setText(_translate("USER_ATC_BUTTONS", "RETR DUST BOOT"))
        self.reference_carousel_4.setProperty("MDICommand", _translate("USER_ATC_BUTTONS", "M13"))
        self.clamp_tool_button.setText(_translate("USER_ATC_BUTTONS", "CLAMP TOOL"))
        self.clamp_tool_button.setProperty("filename", _translate("USER_ATC_BUTTONS", "clamptool.ngc"))
        self.release_tool_button.setText(_translate("USER_ATC_BUTTONS", "RELEASE TOOL"))
        self.release_tool_button.setProperty("rules", _translate("USER_ATC_BUTTONS", "[{\"name\": \"spindle safety\", \"property\": \"Enable\", \"expression\": \"not ch[0]\", \"channels\": [{\"url\": \"status:spindle.0.enabled\", \"trigger\": true}]}]"))
        self.release_tool_button.setProperty("filename", _translate("USER_ATC_BUTTONS", "unclamptool.ngc"))
        self.spindle_orientation.setText(_translate("USER_ATC_BUTTONS", "ORIENT SPINDLE"))
        self.spindle_orientation.setProperty("filename", _translate("USER_ATC_BUTTONS", "orientspindle.ngc"))
        self.unlock_spindle.setToolTip(_translate("USER_ATC_BUTTONS", "M112 User Defined Macro Call from Subroutine Folder"))
        self.unlock_spindle.setText(_translate("USER_ATC_BUTTONS", "UNLOCK SPINDLE"))
        self.unlock_spindle.setProperty("MDICommand", _translate("USER_ATC_BUTTONS", "M5"))
        self.move_head_above_carousel_button.setText(_translate("USER_ATC_BUTTONS", "HEAD UP"))
        self.move_head_above_carousel_button.setProperty("filename", _translate("USER_ATC_BUTTONS", "move_head_above_carousel.ngc"))
        self.move_tool_to_carousel_height_button.setText(_translate("USER_ATC_BUTTONS", "HEAD DOWN"))
        self.move_tool_to_carousel_height_button.setProperty("filename", _translate("USER_ATC_BUTTONS", "move_tool_to_carousel_height.ngc"))
        self.reference_carousel_2.setToolTip(_translate("USER_ATC_BUTTONS", "M13 User Defined Macro Call from Subroutine Folder"))
        self.reference_carousel_2.setText(_translate("USER_ATC_BUTTONS", "REF RACK DATA"))
        self.reference_carousel_2.setProperty("MDICommand", _translate("USER_ATC_BUTTONS", "M13"))
from qtpyvcp.widgets.button_widgets.mdi_button import MDIButton
from qtpyvcp.widgets.button_widgets.subcall_button import SubCallButton
